#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-classworlds
Version  : 1.1.alpha.2
Release  : 4
URL      : https://repo1.maven.org/maven2/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar
Source0  : https://repo1.maven.org/maven2/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar
Source1  : https://repo1.maven.org/maven2/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.pom
Source2  : https://repo1.maven.org/maven2/classworlds/classworlds/1.1/classworlds-1.1.jar
Source3  : https://repo1.maven.org/maven2/classworlds/classworlds/1.1/classworlds-1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Plexus
Requires: mvn-classworlds-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-classworlds package.
Group: Data

%description data
data components for the mvn-classworlds package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/classworlds/classworlds/1.1-alpha-2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/classworlds/classworlds/1.1-alpha-2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/classworlds/classworlds/1.1-alpha-2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/classworlds/classworlds/1.1-alpha-2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/classworlds/classworlds/1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/classworlds/classworlds/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/classworlds/classworlds/1.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/classworlds/classworlds/1.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar
/usr/share/java/.m2/repository/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.pom
/usr/share/java/.m2/repository/classworlds/classworlds/1.1/classworlds-1.1.jar
/usr/share/java/.m2/repository/classworlds/classworlds/1.1/classworlds-1.1.pom
